DROP TABLE book IF EXISTS;

create table book
(
   
   title varchar(255) not null,
   author varchar(255) not null,
   publisher varchar(255) not null,
   publicationDate varchar(255) not null,
   id INTEGER GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL 
   
);

